name: home
timestamp: 1477013217
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1477008823
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-6215: 'Logo / Image'
  menu:
    menu-2427: Menu
  custom:
    custom-8471: 'Custom HTML'
  messages:
    system-messages-2497: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-1146: Copyright
  social:
    social-9486: Social
  mobile-menu:
    mobile-menu-8733: 'Mobile Menu'
inherit: {  }
