name: _error
timestamp: 1477008834
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1477008823
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1323: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-5784: Menu
  messages:
    system-messages-4221: 'System Messages'
  content:
    system-content-1607: 'Page Content'
  copyright:
    copyright-5503: Copyright
  spacer:
    spacer-6078: Spacer
  branding:
    branding-6561: Branding
  mobile-menu:
    mobile-menu-4104: Mobile-menu
inherit: {  }
