version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1477008823
layout:
  /header/:
    -
      - 'logo-1323 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-5784
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-4221
    -
      - system-content-1607
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5503 40'
      - 'spacer-6078 30'
      - 'branding-6561 30'
  offcanvas:
    -
      - mobile-menu-4104
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
