name: _offline
timestamp: 1477008835
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1477008823
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-7948: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-4920: Menu
  messages:
    system-messages-4967: 'System Messages'
  content:
    system-content-7484: 'Page Content'
  copyright:
    copyright-7674: Copyright
  spacer:
    spacer-2666: Spacer
  branding:
    branding-9782: Branding
  mobile-menu:
    mobile-menu-9722: Mobile-menu
inherit: {  }
