version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1477008823
layout:
  /header/:
    -
      - 'logo-7948 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-4920
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-4967
    -
      - system-content-7484
  /footer/:
    -
      - position-footer
    -
      - 'copyright-7674 40'
      - 'spacer-2666 30'
      - 'branding-9782 30'
  offcanvas:
    -
      - mobile-menu-9722
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
